alias: Example – TS004F Button Actions
trigger:
  - platform: event
    event_type: zha_event
    event_data:
      device_id: YOUR_DEVICE_ID
action:
  - choose:
      - conditions:
          - condition: template
            value_template: "{{ trigger.event.data.command == 'press_type' and trigger.event.data.args[0] == 0 }}"
        sequence:
          - service: light.toggle
            entity_id: light.living_room

      - conditions:
          - condition: template
            value_template: "{{ trigger.event.data.command == 'left' }}"
        sequence:
          - service: light.turn_on
            data:
              brightness_step: -25
            target:
              entity_id: light.living_room
